/**
 * Every Spheres of Power/Might/Guile sphere's display name — used by
 * scrape-feats.ts to detect which sphere(s) a feat's Prerequisites text
 * actually names. Kept in sync by hand with the `SPHERES` metadata in
 * scrape-spheres.ts (the canonical source for sphere scraping itself);
 * duplicated here as a flat name list so scrape-feats.ts doesn't need to
 * pull in that script's full scraping machinery just for the names.
 */
export const ALL_SPHERE_NAMES: string[] = [
  // Spheres of Power (magic)
  "Alteration",
  "Blood",
  "Conjuration",
  "Creation",
  "Dark",
  "Death",
  "Destruction",
  "Divination",
  "Enhancement",
  "Fallen Fey",
  "Fate",
  "Illusion",
  "Life",
  "Light",
  "Mana",
  "Mind",
  "Nature",
  "Protection",
  "Technomancy",
  "Telekinesis",
  "Time",
  "War",
  "Warp",
  "Weather",
  // Spheres of Might (martial)
  "Alchemy",
  "Athletics",
  "Barrage",
  "Barroom",
  "Beastmastery",
  "Berserker",
  "Boxing",
  "Brute",
  "Dual Wielding",
  "Duelist",
  "Equipment",
  "Fencing",
  "Gladiator",
  "Guardian",
  "Lancer",
  "Open Hand",
  "Scoundrel",
  "Scout",
  "Shield",
  "Sniper",
  "Trap",
  "Warleader",
  "Wrestling",
  // Spheres of Guile (skill)
  "Artifice",
  "Bluster",
  "Body Control",
  "Communication",
  "Faction",
  "Herbalism",
  "Infiltration",
  "Investigation",
  "Navigation",
  "Performance",
  "Spellhacking",
  "Study",
  "Subterfuge",
  "Survivalism",
  "Vocation",
];
